-- ½ºÄ®¶ó ¼­ºêÄõ¸®
## P6
SELECT A.EMPLOYEE_ID, 
       A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
       A.DEPARTMENT_ID,
       (SELECT B.DEPARTMENT_NAME
        FROM DEPARTMENTS B
        WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) DEPT_NAME 
FROM EMPLOYEES A 
ORDER BY 1;

## P7
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAMES, A.JOB_ID,
(SELECT B.JOB_TITLE || '('  || B.JOB_ID || ')'  
 FROM JOBS B
 WHERE A.JOB_ID = B.JOB_ID) JOB_NAMES
FROM EMPLOYEES A 
ORDER BY 1;

## P10
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME, A.DEPARTMENT_ID,  
(SELECT B.DEPARTMENT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID ) DEPT_NAME
FROM EMPLOYEES A
ORDER BY 1;

## P13 
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME, A.DEPARTMENT_ID,
(SELECT B.DEPARTMENT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID 
) DEPT_NAME,
(SELECT D.COUNTRY_NAME
FROM DEPARTMENTS B, LOCATIONS C, COUNTRIES D
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID 
AND B.LOCATION_ID = C.LOCATION_ID
AND C.COUNTRY_ID = D.COUNTRY_ID
) COUNTRY_NAME
FROM EMPLOYEES A 
ORDER BY 1;

-- ÀÎ¶óÀÎ ºä

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || A.LAST_NAME, A.DEPARTMENT_ID, C.DEPT_NAME
FROM EMPLOYEES A
(SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME DEPT_NAME
FROM DEPARTMENTS B) C
WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID
ORDER BY 1;

## LATERAL P19

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || A.LAST_NAME, A.DEPARTMENT_ID, C.DEPT_NAME
FROM EMPLOYEES A
LATERRAL (SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME DEPT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID) C
ORDER BY 1;

## P20
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
DEPT.DEPARTMENT_NAME, LOC.STREET_ADDRESS, LOC.CITY, LOC.COUNTRY_NAME
FROM EMPLOYEES A
,(SELECT *
FROM DEPARTMENTS B) DEPT
,(SELECT I.LOCATION_ID, I.STREET_ADDRESS, I.CITY, C.COUNTRY_NAME 
FROM LOCATIONS I, COUNTRIES C
WHERE I.COUNTRY_ID = C.COUNTRY_ID) LOC
WHERE A.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
AND DEPT.LOCATION_ID = LOC.LOCATION_ID
ORDER BY 1;

## LATERAL

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
DEPT.DEPARTMENT_NAME, LOC.STREET_ADDRESS, LOC.CITY, LOC.COUNTRY_NAME
FROM EMPLOYEES A
,(SELECT *
FROM DEPARTMENTS B) DEPT
,LATERAL (SELECT I.LOCATION_ID, I.STREET_ADDRESS, I.CITY, C.COUNTRY_NAME 
FROM LOCATIONS I, COUNTRIES C
WHERE I.COUNTRY_ID = C.COUNTRY_ID) LOC
WHERE A.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
AND DEPT.LOCATION_ID = LOC.LOCATION_ID
ORDER BY 1;

## P21

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
DEPT_LOC.DEPARTMENT_NAME,
DEPT_LOC. STREET_ADDRESS, DEPT_LOC.CITY
REG.COUNTRY_NAME, REG.REGION_NAME
FROM EMPLOYEES A
,(SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME, L.STREET_ADDRESS, L.CITY, L.COUNTRY_ID
FROM DEPARTMENTS B, LOCATIONS L
WHERE B.LOCATION_ID = L.LOCATION_ID
) DEPT_LOC
SELECT(L.COUNTRY_ID, C.COUNTRY_NAME 
FROM COUNTRIES C, REGIONS R
WHERE C.REGION_ID = R.REGION_ID) REG
WHERE A.DEPARTMENT_ID, DEPT_LOC.DEPARTMENT_ID
ORDER BY 1;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
DEPT_LOC.DEPARTMENT_NAME,
DEPT_LOC. STREET_ADDRESS, DEPT_LOC.CITY
REG.COUNTRY_NAME, REG.REGION_NAME
FROM EMPLOYEES A
,(SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME, L.STREET_ADDRESS, L.CITY, L.COUNTRY_ID
FROM DEPARTMENTS B, LOCATIONS L
WHERE B.LOCATION_ID = L.LOCATION_ID
) DEPT_LOC
LATERAL SELECT(L.COUNTRY_ID, C.COUNTRY_NAME 
FROM COUNTRIES C, REGIONS R
WHERE C.REGION_ID = R.REGION_ID
AND C.COUNTRY_ID = DEPT_LOC.COUNTRY_ID) REG
WHERE A.DEPARTMENT_ID, DEPT_LOC.DEPARTMENT_ID
ORDER BY 1;

## P23 
SELECT A.DEPARTMENT_ID, A.EMPLOYEE_ID, A.LAST_NAME, A.SALARY,
K.DEPARTMENT_ID SECOND_DEPT_ID, K.AVG_SALARY
FROM EMPLOYEES A
,(SELECT B.DEPARTMENT_ID, AVG(B.SALARY) AVG_SALARY 
FROM EMPLOYEES B
GROUP BY B.DEPARTMENT_ID) K
WHERE A.DEPARTMENT_ID = K.DEPARTMENT_ID
ORDER BY 1;

## P25
SELECT * 
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM EMPLOYEES
                        );

SELECT * 
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID;

SELECT *
FROM LOCATIONS;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM COUNTRIES;

## P6
SELECT A.EMPLOYEE_ID,
       A.FIRST_NAME || A.LAST_NAME,
       A.DEPARTMENT_ID,
      (SELECT B.DEPARTMENT_NAME
         FROM DEPARTMENTS B
        WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) DEPT_NAME
FROM EMPLOYEES A
ORDER BY 1;

## P9
SELECT A.EMPLOYEE_ID, 
       A.FIRST_NAME || ' ' || A.LAST_NAME,
       A.JOB_ID,
       (SELECT JOB_TITLE ||'(' || B.JOB_ID || ')'
       FROM JOBS B
       WHERE A.JOB_ID = B.JOB_ID) JOB_NAMES
FROM EMPLOYEES A
ORDER BY 1; 
 
## P10
SELECT A.EMPLOYEE_ID, 
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
A.DEPARTMENT_ID,
B.DEPARTMENT_NAME
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
ORDER BY 1;

SELECT A.EMPLOYEE_ID, 
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
A.DEPARTMENT_ID,
(SELECT B.DEPARTMENT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID)DEPT_NAME
FROM EMPLOYEES A
ORDER BY 1;

## P12
SELECT A.EMPLOYEE_ID, 
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
A.DEPARTMENT_ID,
B.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON A.DEPARTMENT_ID = B.DEPARTMENT_ID
ORDER BY 1;

SELECT A.EMPLOYEE_ID, 
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
A.DEPARTMENT_ID,
(SELECT B.DEPARTMENT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID)DEPT_NAME
FROM EMPLOYEES A
ORDER BY 1;

## P13
SELECT A.EMPLOYEE_ID,
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
A.DEPARTMENT_ID,
(SELECT B.DEPARTMENT_NAME
FROM DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) DEPT_NAME,
(SELECT D.COUNTRY_NAME
FROM DEPARTMENTS B, LOCATIONS C, COUNTRIES D
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND B.LOCATION_ID = C.LOCATION_ID
AND C.COUNTRY_ID = D.COUNTRY_ID) COUNTRY_NAME
FROM EMPLOYEES A
ORDER BY 1;

## P17
SELECT A.EMPLOYEE_ID,
A.FIRST_NAME || '' || A.LAST_NAME,
A.DEPARTMENT_ID,
C.DEPT_NAME
FROM EMPLOYEES A,
    (SELECT B.DEPARTMENT_ID, 
     B.DEPARTMENT_NAME DEPT_NAME
     FROM DEPARTMENTS B) C
WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID
ORDER BY 1;


SELECT A.EMPLOYEE_ID,
A.FIRST_NAME || '' || A.LAST_NAME,
A.DEPARTMENT_ID,
C.DEPT_NAME
FROM EMPLOYEES A,
    LATERAL
    (SELECT B.DEPARTMENT_ID, 
     B.DEPARTMENT_NAME DEPT_NAME
     FROM DEPARTMENTS B
     WHERE A.DEPARTMENT_ID = C.DEPARTMENT_ID) C
ORDER BY 1;

## P20

SELECT A.EMPLOYEE_ID,
A.FIRST_NAME || ' ' || A.LAST_NAME EMP_NAME,
DEPT.DEPARTMENT_NAME,
LOC.STREET_ADDRESS, LOC.CITY,
LOC.COUNTRY_NAME
FROM EMPLOYEES A,
    (SELECT *
     FROM DEPARTMENTS B) DEPT,
    (SELECT L.LOCATION_ID, L.STREET_ADDRESS,
     L.CITY, C.COUNTRY_NAME
     FROM LOCATIONS L, COUNTRIES C 
     WHERE L.COUNTRY_ID = C.COUNTRY_ID) LOC
WHERE A.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
AND DEPT.LOCATION_ID = LOC.LOCATION_ID
ORDER BY 1;

# P22
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || LAST_NAME
FROM EMPLOYEES A,
(SELECT B.DEPARTMENT_ID, B.DEPARTMENT_NAME, L.STREET_ADDRESS, L.CITY, L.COUNTRY_NAME
FROM DEPARTMENTS B, LOCATIONS L
WHERE B.DEPARTMENT_ID ) DEPT_LOC,
LATERAL(SELECT C.COUNTRY_ID, C.COUNTRY_NAME, R.REGION_NAME
FROM COUNTRIES C, REGIONS R
WHERE C.REGION_ID = R.REGION_ID
AND C.COUNTRY_ID = DEPT_LOC.COUNTRY_ID)REG
WHERE A.DEPARTMENT_ID = DEPT_LOC.DEPARTMENT_ID 
ORDER BY 1;

## P23
SELECT A.DEPARTMENT_ID, A.EMPLOYEE_ID, A.LAST_NAME, A.SALARY, 
K.DEPARTMENT_ID SECOND_DEPT_ID, K.AVG_SALARY
FROM EMPLOYEES A,
(SELECT B.DEPARTMENT_ID, AVG(B.SALARY) AVG_SALARY
FROM EMPLOYEES B
GROUP BY B.DEPARTMENT_ID) K
WHERE A.DEPARTMENT_ID = K.DEPARTMENT_ID
ORDER BY A.DEPARTMENT_ID;

## P25
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                        FROM EMPLOYEES
                        );

## 26
SELECT *
FROM DEPARTMENTS A 
WHERE EXISTS
(SELECT 1
FROM EMPLOYEES B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
);

## P27
SELECT *
FROM DEPARTMENTS A
WHERE EXISTS (SELECT 'A'
             FROM EMPLOYEES B 
             WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
             AND B.SALARY > 10000);

## P28
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME EMP_NAME, JOB_ID, SALARY 
FROM EMPLOYEES 
WHERE (JOB_ID, SALARY) IN (SELECT JOB_ID, MIN_SALARY
                             FROM JOBS) 
ORDER BY 1;

## P29

SELECT LAST_NAME, EMPLOYEE_ID, SALARY + NVL(COMMISSION_PCT, 0) TOT_SALARY, JOB_ID, E.DEPARTMENT_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE e.department_id = d.department_id
AND SALARY + NVL(COMMISSION_PCT, 0) >
(SELECT SALARY + NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES
WHERE LAST_NAME = 'Pataballa')
ORDER BY LAST_NAME, EMPLOYEE_ID;

SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES A 
WHERE SALARY >
(SELECT AVG(SALARY)
FROM EMPLOYEES B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

## 31 
SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES A 
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES A
GROUP BY DEPARTMENT_ID
ORDER BY 1;

## P32
SELECT DEPARTMENT_ID, EMPLOYEE_ID, LAST_NAME,SALARY 
FROM EMPLOYEES A 
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES B
                WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

## P33
SELECT *
FROM DEPARTMENTS A 
WHERE EXISTS
     (SELECT 1
     FROM EMPLOYEES B
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID);


## P34
SELECT *
FROM DEPARTMENTS A 
WHERE NOT EXISTS
     (SELECT 1
     FROM EMPLOYEES B
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID);

## P35
SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME
FROM EMPLOYEES A
WHERE A.EMPLOYEE_ID 
            NOT IN (SELECT EMPLOYEE_ID
                    FROM JOB_HISTORY)
ORDER BY 1;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME || ' ' || A.LAST_NAME
FROM EMPLOYEES A
WHERE NOT EXISTS (SELECT 0
                  FROM JOB_HISTORY B
                  WHERE A.EMPLOYEE_ID = B.EMPLOYEE_ID)
ORDER BY 1;
